services:
  les-discord-webhook:
    # build: .
    image: ghcr.io/leipzigesports/les-discord-webhook:latest
    container_name: les-discord-webhook
    volumes:
      - ./config.json:/app/config.json